### ISSUE TITLE
std namespace

### ISSUE THREAD

**Issue by m2q** [AdamStelmaszczyk/gtsa#22]
Your gtsa header is 

```C++
using namespace std;
```

I think you should remove it, because if I use your header the standard namespaces could clash with my own implementations (or someone might not notice it uses the wrong library)

**Comment by AdamStelmaszczyk** [comment]
Thanks, fixed in https://github.com/AdamStelmaszczyk/gtsa/commit/803815e425904f67db04a9546760c251f9217403.
