### ISSUE TITLE
Mirror library in C++

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [AdamStelmaszczyk/gtsa#6]
Currently only Python library is available. In parallel to it, mirror library will be available, in C++.

Python was chosen because of the speed and ease of development and prototyping. New features and upgrades will be always implemented and tested there first.

However, Python is unfortunately much slower than compiled C++. So, to gain probably like 10-100x speed up there will be a mirror library, a port from Python to C++. Performance is important, 100x speed up means 100x more simulations (within the time limit which always exists during competitions).

The libraries will be both in the same repository. There will be two root directories - `python` and `cpp`.

**Comment by ysa111** [comment]
what is this?

**Comment by AdamStelmaszczyk** [comment]
@ysa111 Thanks for your comment :) I updated the title and the description.

**Comment by AdamStelmaszczyk** [comment]
I did a simple performance test: 

How many MCTS simulations Python and C++ (on -O2) will make during 1 second in Tic Tac Toe? 

I've run it 10 times for one language and final number of simulations was the average from runs.

Python: 2300
C++: 82000

That's about 36 times more.
